[package]
name = "if_else_sample"
version = "0.1.0"
authors = ["Uzurachan <bussiness.ack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
